name: docker-ci-awslc

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          vers:
          - "v3.2.9"
          - "v3.3.6"
          - "v3.2.15"
          - "v3.1.17"
          - "v3.0.19"
          - "v2.9.15"
          # - "v2.8.19"
          # Supported since HAProxy 2.9,
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v4
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v4
      -
        name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      # - name: Dynamic alignment version
      #   id: alignment
      #   run: |
      #     HAPROXY_VERSION="${{ matrix.vers }}"
      #     BASE_VER=${HAPROXY_VERSION#v}
      #     OPENSSL_VERSION=$(docker run --rm haproxy:${BASE_VER}-alpine -vv   |  grep "OpenSSL" |grep version | head -n1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+[a-z]?')
      #     echo ::set-output name=OPENSSL_VERSION::${OPENSSL_VERSION}

      # - name: Test Dynamic alignment version
      #   run: |
      #     echo ${{ steps.alignment.outputs.OPENSSL_VERSION }}

      - name: Build dockerfile (without push)
        run: |
          dynamic_args=()
          # OPENSSL_VERSION="${{ steps.alignment.outputs.OPENSSL_VERSION }}"
          # if [ -n "${OPENSSL_VERSION}" ]; then
          #   dynamic_args+=(--OPENSSL_VERSION ${OPENSSL_VERSION})
          # fi

          dynamic_args+=("--USE_OPENSSL_AWSLC" "1")
          dynamic_args+=("--USE_QUIC" "1")

          ./buildx.sh --push false --repo ${{ secrets.DOCKER_USERNAME }} --HAPROXY_VERSION ${{ matrix.vers }} ${dynamic_args[*]}

      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build dockerfile (with push)
        run: |
          dynamic_args=()
          # OPENSSL_VERSION="${{ steps.alignment.outputs.OPENSSL_VERSION }}"
          # if [ -n "${OPENSSL_VERSION}" ]; then
          #   dynamic_args+(--OPENSSL_VERSION ${OPENSSL_VERSION})
          # fi
          dynamic_args+=("--USE_OPENSSL_AWSLC" "1")
          dynamic_args+=("--USE_QUIC" "1")
          ./buildx.sh --push true --repo ${{ secrets.DOCKER_USERNAME }} --HAPROXY_VERSION ${{ matrix.vers }} ${dynamic_args[*]}
